name = "react-component"  # Name your project (must be unique in your Cloudflare account)
compatibility_date = "2025-03-02"  # Use today’s date

# Configure as a Workers Site (static site)
[site]
bucket = "./build"  # Path to your static files